# One-time: create upload-release.jks + keystore.properties for signed release builds.
# Output stays in this folder (gitignored). Re-run only if you intentionally replace the keystore.
#
# WARNING: Do not re-run if upload-release.jks already exists. Register its SHA256 on BOTH
# Play Console (App signing upload key) and Google developer verification, then keep this file.
$ErrorActionPreference = "Stop"

$androidDir = $PSScriptRoot
$jks = Join-Path $androidDir "upload-release.jks"
$props = Join-Path $androidDir "keystore.properties"
$credNote = Join-Path $androidDir "SIGNING-CREDENTIALS-LOCAL.txt"

if (Test-Path -LiteralPath $jks) {
    throw "upload-release.jks already exists. Delete it first only if you mean to replace the upload key."
}
if (Test-Path -LiteralPath $props) {
    throw "keystore.properties already exists. Remove it first if regenerating."
}

function New-RandomPassword([int]$Length = 24) {
    $chars = (48..57) + (65..90) + (97..122)
    -join (1..$Length | ForEach-Object { [char]($chars | Get-Random) })
}

$storePass = New-RandomPassword
$keyPass = $storePass
$alias = "upload"
$dname = "CN=Root Units Idle Farmer, OU=Root Record, O=Root Record, C=US"

$keytool = Get-Command keytool -ErrorAction SilentlyContinue
if (-not $keytool) {
    throw "keytool not on PATH. Install JDK 17+ or open a shell where Android Studio's JDK is configured."
}

Push-Location $androidDir
try {
    & keytool -genkeypair -v `
        -storetype PKCS12 `
        -keystore "upload-release.jks" `
        -alias $alias `
        -keyalg RSA `
        -keysize 2048 `
        -validity 10000 `
        -storepass $storePass `
        -keypass $keyPass `
        -dname $dname
    if ($LASTEXITCODE -ne 0) { throw "keytool failed with exit $LASTEXITCODE" }
} finally {
    Pop-Location
}

@(
    "# Generated by setup-release-signing.ps1 (do not commit)",
    "storePassword=$storePass",
    "keyPassword=$keyPass",
    "keyAlias=$alias",
    "storeFile=upload-release.jks"
) | Set-Content -LiteralPath $props -Encoding ASCII

@"
Root Farms Android upload key - BACK UP THEN DELETE THIS FILE
Generated: $(Get-Date -Format o)

keystore: $androidDir\upload-release.jks
alias:    $alias
storePassword: $storePass
keyPassword:   $keyPass

Package: com.rootrecord.rootunits
Play Console: upload release AAB from Mobile\builds\root-farms\
Export upload_certificate.pem for developer verification after first keytool -exportcert
"@ | Set-Content -LiteralPath $credNote -Encoding UTF8

Write-Host "Created:" -ForegroundColor Green
Write-Host "  $jks"
Write-Host "  $props"
Write-Host "  $credNote  (save passwords, then delete this file)"
Write-Host ""
Write-Host "Re-run bump-and-build-release.bat for signed APK + AAB."
